package com.example.Student_library_management.Models;

import com.example.Student_library_management.Enums.CardStatus;
import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.util.Date;

@Entity
@Table(name="card")
public class Card {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id; //This is autogenerated

    @CreationTimestamp
    private Date createdOn;  //Auto time stamp when entry is created
    //This is autogenerated

    @UpdateTimestamp
    private Date updatedOn; //sets time when an entry is updated
    //This is autogenerated

    @Enumerated(value = EnumType.STRING)
    private CardStatus cardStatus;   //Need to set the attr.

    @OneToOne
    @JoinColumn
    private Student studentvariable; //This variable is used in parent class while doing the bidirectional mapping
    //Ye foreign key hai isko set karna padega


    public Student getStudentvariable() {
        return studentvariable;
    }

    public void setStudentvariable(Student studentvariable) {
        this.studentvariable = studentvariable;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public CardStatus getCardStatus() {
        return cardStatus;
    }

    public void setCardStatus(CardStatus cardStatus) {
        this.cardStatus = cardStatus;
    }





    public Card() {
    }
}
